#!/bin/bash

IFS='
'
red='\e[0;31m'
green='\e[0;32m'
NC='\e[0m'
bold=`tput bold`
normal=`tput sgr0`
input=`cat input`

if [ ! -e "Parser.cpp" ] ; then
    echo "Make sure Parser.cpp is in this directory."
    exit 1
elif [ ! -e "solution" ] || [ ! -e "input" ] ; then
    echo "Make sure the 'solution' and 'input' files are in this directory."
    exit 2
fi

g++ -oParser Parser.cpp
./Parser <<EOF > output
$input
EOF

numlines=`wc -l < solution`
numfail=0

for i in `seq 1 $numlines` ; do
    solline=`sed "${i}q;d" solution`
    outline=`sed "${i}q;d" output`
    inline=`sed "${i}q;d" input`
    if [ ! "$solline" = "$outline" ] ; then
        numfail=$((numfail + 1))
        echo -e "********************"
        echo -e "${red}Failed${NC} unit test ${bold}$i${normal}: "
        echo "$inline" 
        echo "Expected: "
        echo "$solline"
        echo "Your program outputted: "
        echo "$outline"
        echo -e "********************\n"
    fi

done

if [ $numfail = 0 ] ; then
    echo -e "Summary: ${green}All unit tests passed.${NC}"
else
    echo -e "Summary: $numfail / $numlines ${red}${bold}failed${NC}${normal} unit tests."
fi
